apiVersion: apps/v1
kind: Deployment
metadata:
  name: govcy-design-system
  labels:
    app: govcy-design-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: govcy-design-system
  template:
    metadata:
      labels:
        app: govcy-design-system
    spec:
      #imagePullSecrets:
      #- name: regcred
      containers:
      - name: govcy-design-system
        image: ghcr.io/gov-cy/govcy-design-system:main
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "200Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
          - containerPort: 80