name: Percy CI
on: 
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
   branches:
     - main
  pull_request:
    branches:
     - main
jobs:
  build:
    name: Percy Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - run: |
        npm install ci
        npx percy --version
        npx percy exec -- mocha --recursive --exit
    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
