name: Sass

on: [pull_request]
  branches-ignore:
    - '**'
jobs:
  dart-sass:
    name: Dart Sass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: |
          npm install ci
          npm exec -c "sass --version"
      - run: npm run css-build 