name: Tag and Publish on Version Change

on:
  pull_request:
    branches:
      - main
jobs:
  tag-and-publish-on-version-change:
    name: Tag and Publish to CDN on Version Change
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: EndBug/version-check@v2.1.0
        with:
          diff-search: true
          # format: "{name}_v{version}+build.{pr_number}.zip"
        id: version-check
        

      - run: |
          echo "name: ${{ steps.version-check.outputs.changed }}"
          echo "name: ${{ steps.version-check.outputs.type }}"
          echo "name: ${{ steps.version-check.outputs.version }}"
          echo "name: ${{ steps.version-check.outputs.commit }}"