name: Sanity Check Version Number/ File Changes

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - dist
jobs:
  version-sanity-checks:
    name: Sanity Check Version Number/ File Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/version-check@v2.1.0
        with:
          static-checking: localIsNew
          file-url: https://raw.githubusercontent.com/gov-cy/govcy-design-system/latest/package.json
        id: version-check
      - if: steps.check.outputs.changed == 'true' && steps.check.outputs.changed == 'undefined'
        run: echo "You should NEVER decrement/ decrease the version in the package.json. This will undermine confidence in our ability to follow semver rules"; exit 1
      - if: steps.check.outputs.changed == 'false'
        run: echo "You have updated the distribution without incrementing the version number. You must update package.json::version to publish a new version"; exit 1
